python src/fine_tuning/run_clm_no_trainer.py \
    --model_name_or_path mistralai/Mistral-7B-Instruct-v0.2 \
    --train_file data/splits/train.csv \
    --validation_file data/splits/val.csv \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --gradient_accumulation_steps 1 \
    --lr_scheduler_type linear \
    --num_warmup_steps 0 \
    --learning_rate 3e-4 \
    --lora_attention_dim 8 \
    --lora_alpha 32 \
    --lora_dropout 0.1 \
    --num_train_epochs 3 \
    --seed 42 \
    --report_to wandb \
    --output_dir runs